### ISSUE TITLE
Very awesome work, thanks for contributing!

### ISSUE THREAD

**Issue by ZubinGou** [yifanzhang-pro/AutoMathText#1]
This dataset is a fantastic contribution! May I ask if you could share the GPUs and time required to filter out these corpora? Also, could you share the prompts for Qwen you used?

**Comment by yifanzhang-pro** [comment]
We are writing the paper now, details will be updated soon!

**Comment by yifanzhang-pro** [comment]
Prompts have been released in README!

**Comment by ZubinGou** [comment]
Thank you for the release, it looks promising!
