### ISSUE TITLE
Similarity based reranking for curriculum-based learning or step by step reward modeling

### ISSUE THREAD

**Issue by TimeLordRaps** [yifanzhang-pro/AutoMathText#2]
Thank you for your effort in constructing this dataset.
Not quite sure if this could be valuable or not, but this project seems so close to an automatic math curriculum.
I'm thinking some sort of ordered pairwise semantic retrieval based meta-prompting strategy may work, I haven't thought to deeply about it but maybe you could even use the values you've already calculated as a way to order the retrievals. 

I'm not sure which side of the curriculum to start on though. You could take the highest-ranking original label and try to find previously valuable related information which might work if you have a smart enough embedding model. 

Or instead set some minimum threshold of Qwen value and start from there and for each increasing Qwen value datapoint find the k most similar datapoints possibly factoring in the Qwen rankings into the embeddings or using it as some weighting. 
Then use Qwen to compare 1 x 1 a dynamic number of the most similar datapoints to the query datapoint to create weighted edges between those datapoints that represent the necessity of the query to understanding the dynamic number. 

I think a dynamic number would be better to get a near constant number of links. 
So, like until k links have been found with values above some threshold, keep searching through the semantically retrieved similar points. This threshold might need to be adjusted based on the average/range of the similarity scores of retrieved datapoints.

While not a complete representation of all the edges. I really think this would be incredibly valuable as a means for step-by-step reward modeling.

**Comment by yifanzhang-pro** [comment]
Thank you for your innovative suggestion on organizing the AutoMathText dataset into a curriculum-like format using semantic retrieval and Qwen-72B scores. We appreciate your idea of dynamically linking mathematical texts based on relevance and similarity to create a guided learning experience. Your approach of starting with high-quality content or a minimum relevance threshold, and dynamically adjusting searches to maintain a consistent number of conceptually linked topics, offers a promising method for structured learning. We will consider your proposal as we aim to enhance AutoMathText's educational value. Your input is invaluable to our project's development.

**Comment by TimeLordRaps** [comment]
In rereading my issue I see that I should elaborate on some things:
Ordered pairwise semantic retrieval based meta-prompting strategy:
Ordered because you already have the Qwen value and can sort based on that
Pairwise because you would be creating a semantically valuable directed edge between the query node and each of the semantically retrieved nodes.

How I would factor the currently available Qwen values into similarity score:
If starting from the high Qwen value nodes and reverse engineering ways to get there, I would want to look more at lower Qwen values.
If starting from minimum threshold I probably wouldn't consider anything below it, but when searching for neighbors I probably wouldn't want to be searching for values greater than some threshold away from the current nodes Qwen value.

Dynamic search space:
Intuition: some ideas require more ideas as direct pre-requisites
Dynamic because as one expands the pool of searched semantically relevant documents by moving through the ordering of returned documents, they should be evaluating each not only on their relevancy to the query document and Qwen value, but also on their ability to be a pre-requisite for the query document. Then with the prerequisiteness of the returned document to the query document a decision should be made to continue through to the next relevant document or claim you have found a sufficient sample of the prerequisites necessary to learn the query subject and/or enough samples to create sufficient structure within the overall graph for some graph completion algorithms to handle analogous, ambiguous, and overlapping documents.

Current flaws:
Multi-level pre-requisites:
If one idea requires an idea that itself is required by an idea the original idea requires, you end up with unaligned stepping stones, despite this being a very real scenario
integration needs multiplication and addition as valuable concepts first, and multiplication needs addition.

This leads to the question what representation of an ordering is most complete.
Considering learning seems to me at least to be typically cyclical/recursive in nature it might be valuable to eventually add a meta-learning annotation on top of the edges where the edges themselves would be represented by a token representation of the natural language expression of the semantics of the relationship between two documents in order to create not only a more nuanced graph, but a valuable multi-modal dataset from which we could learn the general edge function between concepts which could further refine the graph by filling in high confidence missing edges, but also enrich our own understanding on the nature of conceptual requirement.

**Comment by yifanzhang-pro** [comment]
Interesting ideas, can you provide us with some practical pseudo algorithm or something?

**Comment by TimeLordRaps** [comment]
```
# Note uses a simple scheduling system I came up with on the spot so I'm sure there is room for improvement.

documents = [{
    documentText: the text for the document
    qwenScore: the evaluated Qwen score from the AutoMathText project.
}]
# each of the following is set to some default value that I think is representative of what the values are, not good values to actually use.
startingMinimumSimilarityThreshold = 1 # Shouldn't be higher than this
absoluteMinimumSimilarityThreshold = 0 # Shouldn't be lower than this
startingMaximumQwenDifference = 1 # Shouldn't be higher than this
absoluteMaximumQwenDifference = -1 # Shouldn't be lower than this
minNumResults = 8 # arbitrary
maxNumResults = 8 # arbitrary
minIterations = 2 # arbitrary
maxIterations = 4 # arbitrary
# startingMinimumSimilarityThreshold is the minimum similarity threshold for the first iteration of the search. You want to set this high to get the most relevant results first and progressively look at less relevant results as you go on.
# absoluteMinimumSimilarityThreshold is the minimum similarity threshold for the last iteration of the search. You want to set this lower but not too low to get the most relevant results first and progressively look at less relevant results as you go on.
# startingMaximumQwenDifference is the maximum difference in Qwen score for the first iteration of the search.
# absoluteMaximumQwenDifference is the maximum difference in Qwen score for the last iteration of the search.
# minNumResults is the minimum number of results you want to get from the search.
# minIterations is just useful in combination with maxNumResults as a way to layer the search.
# maxIterations is the maximum number of iterations you want to do. This is important because you don't want to spend too much time on a search where each progressive layer of search is arguably less and less important to the overall graph.
# NOTE: I'm not sure what a good startingMaximumQwenDifference and absoluteMaximumQwenDifference would be because there are a few options which each have their own compute budget and implementation differences, and all of these only consider the similarity regime I already laid out.
    # Example 1: Start close to 1 and then end close to -1. (This is the one I will implement)
        Creating outgoing edges from the document to positive differences representing the document as a pre-requisite for the positive differenced documents. 
        And incoming edges to the document from negative differences representing the document as having the negative differenced documents as pre-requisites.
    # Example 2: Start at 0 and then end close to -1. 
        Only gets pre-requisites of the document, not documents the document is a pre-requisite for, 
        This limits the complexity of the search, while in my opinion not losing much information in the overall graph because we are still representing the exact same pre-requisite relationships, just not necessarily in a bi-directional way, which may not even be desirable.
    # Example 3: Start at 0 and then end close to 1.
        Basically the same arguement as example 2, but in the opposite direction.


function similarity(query, documents):
    # function that does some similarity metric over the query embedding and the embeddings in the vector database and returns a sorted list based on similarity.
    tempDocuments = documents # you don't want to modify the order of the original documents because their order matters for the outer loop
    for i in range(len(documents)):
        tempDocuments[i][similarity] = similarity_metric(query, tempDocuments[i][documentText]) 
    sort(tempDocuments, tempDocument[similarity]) # sort by similarity
    return tempDocuments

function retrieve_documents(documentID, documents):
    prompt = modify_document_for_semantic_search(document) # just some function for optimizing the document to be a search query
    # Note: I don't know that much literature on this type of prompt engineering so maybe experimenting with this first as a means for optimizing for importance of prerequisities in the search results, would be a crucial determining step in the efficacy of the overall graph. 
        # As well, using a good embedding model capable of long document embeddings would impact the quality of the overall graph. Embedding models are another thing I know very little about, but to my knowledge at this time, the best models are only capable of 32k contexts, but the new 1 million token Large World Models maybe transformable into some sort of long form embedding model.
    similarityResults = similarity(prompt, documents)
    minimumSimilarityThresholds = linspace(startingMinimumSimilarityThreshold, absoluteMinimumSimilarityThreshold, maxIterations)
    maximumQwenDifferences = linspace(startingMaximumQwenDifference, absoluteMaximumQwenDifference, maxIterations)
    iterations = 0
    prereqs = []
    postreqs = []
    while(len(results) < minNumResults or iterations < minIterations):
        for document in similarityResults:
            if document["similarity"] > minimumSimilarityThresholds[iterations]:
                if maximumQwenDifferences[iterations] > 0:
                    if document["qwenScore"] - documents[documentID]["qwenScore"] > 0:
                        if document["qwenScore"] - documents[documentID]["qwenScore"] < maximumQwenDifferences[iterations]:
                            prereqs.append(document)
                else: # logic just incase it helps, but in theory this is just excessive computations, but can be avoided by only using positive maximumQwenDifference values.
                    if document["qwenScore"] - documents[documentID]["qwenScore"] < 0:
                        if document["qwenScore"] - documents[documentID]["qwenScore"] > maximumQwenDifferences[iterations]:
                            postreqs.append(document)
        iterations += 1
        if(len(prereqs) + len(postreqs) > maxNumResults):
            break
        if iterations > maxIterations:
            break
    return prereqs, postreqs

documents = documents.sort("qwenScore")
for i in range(len(documents)):
    prereqs, postreqs = retrieve_documents(i, documents)
    for prereq in prereqs:
        add_edge(prereq, documents[i])
    for postreq in postreqs:
        add_edge(documents[i], postreq)
```

Hope this is clear enough for what I am imagining. However the use of linspace as a schedule is naive. Realistically you probably would want to start by expanding the search very little in either direction of similarity or QwenScore then increase the magnitude of which you expand the search

**Comment by TimeLordRaps** [comment]
In the area of the code where the pre-req's or post-req's are appended you can also add an extra filtering step that uses Qwen again to score based on specific pre-req and post-req prompting strategies with another set of thresholds to gate layers of the search based on this.
Also saving/caching of these responses would be necessary for this addition and general better state management would be helpful in respect to existing pseudocode, because on each iteration you are revisiting past examples under new thresholds.

**Comment by yifanzhang-pro** [comment]
Great! We'll carefully consider it.

**Comment by TimeLordRaps** [comment]
Looks like someone at Qwen listened lol.
