### ISSUE TITLE
potential wrong index in processing scripts

### ISSUE THREAD

**Issue by SUDA-HLT-ywfang** [yifanzhang-pro/AutoMathText#4]
Hi, I have some problems trying to reproduce the scores on web data. I read the processing script and wonder if this is a bug (the index of q2 logprobs is the same as q1).

https://github.com/yifanzhang-pro/AutoMathText/blob/master/src/process-web-data.py#L180

**Comment by yifanzhang-pro** [comment]
Thanks for your attention! The code has been updated.

**Comment by SUDA-HLT-ywfang** [comment]
Could you review the data score after fixing it please? I observe a significant score gap after I fix the bug here, e.g. 0.90+ before --> 0.5+ after fixing the bug.

**Comment by yifanzhang-pro** [comment]
I think the threshold might need to be changed accordingly, since you only need to get relative score, not absolute score.
